spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/static/**
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"



logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.view: TRACE
    org.apache.jasper: DEBUG
    org.apache.catalina.core.ApplicationDispatcher: TRACE
    com.ip_project: DEBUG
server:
  port: 8081
  servlet:
    context-path: /
debug: true